TESTS WITH ERRORS 
test14 (gradingtests.UnitTests)
Traceback (most recent call last):
  File "/Users/k2i/academics/automatedgradingapp/app/testing/kb-inference/gradingtests.py", line 405, in test14
    KB.kb_retract(fact2)
  File "/Users/k2i/academics/automatedgradingapp/app/testing/kb-inference/student_code.py", line 215, in kb_retract
    self.kb_remove(fact) #remove fact from knowledge base
  File "/Users/k2i/academics/automatedgradingapp/app/testing/kb-inference/student_code.py", line 147, in kb_remove
    for currPair in currFact.supported_by:
AttributeError: 'NoneType' object has no attribute 'supported_by'

-------------------------------
TESTS FAILED  
-------------------------------
TESTS SKIPPED 
-------------------------------
